// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI flow that generates a supportive and encouraging response to a user's stated daily intentions.
 *
 * - generateEncouragingResponse - A function that generates an encouraging response to user intentions.
 * - GenerateEncouragingResponseInput - The input type for the generateEncouragingResponse function.
 * - GenerateEncouragingResponseOutput - The return type for the generateEncouragingResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEncouragingResponseInputSchema = z.object({
  intention: z.string().describe('The user\'s stated daily intention or goal.'),
});
export type GenerateEncouragingResponseInput = z.infer<typeof GenerateEncouragingResponseInputSchema>;

const GenerateEncouragingResponseOutputSchema = z.object({
  response: z.string().describe('The AI-generated supportive and encouraging response.'),
});
export type GenerateEncouragingResponseOutput = z.infer<typeof GenerateEncouragingResponseOutputSchema>;

export async function generateEncouragingResponse(input: GenerateEncouragingResponseInput): Promise<GenerateEncouragingResponseOutput> {
  return generateEncouragingResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEncouragingResponsePrompt',
  input: {schema: GenerateEncouragingResponseInputSchema},
  output: {schema: GenerateEncouragingResponseOutputSchema},
  prompt: `You are a supportive and encouraging AI assistant designed to help users stay motivated and focused on their goals. When a user states their daily intention, generate a brief, uplifting response to encourage them.

User Intention: {{{intention}}}

Encouraging Response:`, 
});

const generateEncouragingResponseFlow = ai.defineFlow(
  {
    name: 'generateEncouragingResponseFlow',
    inputSchema: GenerateEncouragingResponseInputSchema,
    outputSchema: GenerateEncouragingResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
