
"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export function TermsContent() {
    return (
        <div className="max-w-4xl mx-auto space-y-8">
            <Card>
                <CardHeader className="text-center">
                    <CardTitle className="font-headline text-4xl">ZenJar App Terms of Service</CardTitle>
                    <CardDescription>
                        Last Updated: July 30, 2025
                    </CardDescription>
                </CardHeader>
                <CardContent className="text-base text-foreground/80 space-y-6 prose dark:prose-invert max-w-none">
                    <p>Please read these Terms of Service ("Terms") carefully before using the ZenJar application (the "App"), including its web, browser extension, and chat bot integrations (Slack, Discord), and any related services provided by ZenJar ("we," "us," or "our").</p>
                    <p>By accessing or using the App, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, do not use the App.</p>

                    <h2 className="font-headline">1. Acceptance of Terms</h2>
                    <p>By creating an account, accessing, or using the ZenJar App, you acknowledge that you have read, understood, and agree to be bound by these Terms, as well as any additional terms and conditions or policies referenced herein or made available on the App.</p>

                    <h2 className="font-headline">2. Eligibility and User Accounts</h2>
                    <h3 className="font-headline">Eligibility</h3>
                    <p>You must be at least 13 years old to use the App. By using the App, you represent and warrant that you meet this age requirement.</p>
                    <h3 className="font-headline">Account Creation</h3>
                    <p>You can create an account using your Google Account or by starting anonymously. If you begin anonymously, your data may be associated with a temporary ID until you link a permanent account.</p>
                    <h3 className="font-headline">Account Security</h3>
                    <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to protect your account.</p>

                    <h2 className="font-headline">3. License to Use the App</h2>
                    <p>Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the ZenJar App for your personal, non-commercial use.</p>

                    <h2 className="font-headline">4. User Responsibilities and Conduct</h2>
                    <p>You agree to use the App only for lawful purposes and in a manner that does not infringe the rights of, or restrict or inhibit the use and enjoyment of the App by any third party. Specifically, you agree not to:</p>
                    <ul className="list-disc pl-6">
                        <li>Use the App for any illegal or unauthorized purpose.</li>
                        <li>Transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
                        <li>Upload or transmit any viruses, malware, or any other harmful code.</li>
                        <li>Attempt to gain unauthorized access to the App, other user accounts, or our systems.</li>
                        <li>Interfere with or disrupt the integrity or performance of the App.</li>
                        <li>Use any automated system, including "robots," "spiders," or "offline readers," to access the App in a manner that sends more request messages to our servers than a human can reasonably produce in the same period by using a conventional web browser.</li>
                        <li>Reproduce, duplicate, copy, sell, resell, or exploit any portion of the App without our express written permission.</li>
                        <li>Misrepresent your identity or affiliation.</li>
                    </ul>

                    <h2 className="font-headline">5. AI-Powered Features and Content</h2>
                    <p>ZenJar utilizes Artificial Intelligence (AI) to provide features such as task categorization, prioritization, and supportive responses.</p>
                    <h3 className="font-headline">AI Output</h3>
                    <p>The output generated by our AI features (e.g., task categories, motivational responses) is for informational and organizational purposes only. While we strive for accuracy and helpfulness, AI output may not always be perfect, complete, or suitable for all situations. You are solely responsible for reviewing and acting upon any AI-generated content.</p>
                    <h3 className="font-headline">User Input</h3>
                    <p>You retain ownership of the content you input into the App. By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content solely for the purpose of operating, improving, and developing the ZenJar App and its features (including training and improving our AI models).</p>

                    <h2 className="font-headline">6. Freemium Model and ZenJar Pro</h2>
                    <h3 className="font-headline">Free Tier</h3>
                    <p>ZenJar offers a free tier with core functionalities, subject to certain usage limits (e.g., number of active tasks, gratitude entries).</p>
                    <h3 className="font-headline">ZenJar Pro</h3>
                    <p>We offer a premium subscription service ("ZenJar Pro") that provides access to enhanced features, increased limits, and additional integrations.</p>
                    <h3 className="font-headline">Billing</h3>
                    <p>If you subscribe to ZenJar Pro, you agree to the pricing and payment terms presented to you at the time of subscription. All payments are processed through third-party payment processors (e.g., Stripe, RevenueCat), and you agree to their terms and conditions. Subscriptions may auto-renew unless canceled.</p>
                    <h3 className="font-headline">Cancellations</h3>
                    <p>You may cancel your ZenJar Pro subscription at any time through your account settings or by contacting our support. Cancellations will take effect at the end of your current billing cycle.</p>
                    
                    <h2 className="font-headline">7. Third-Party Integrations</h2>
                    <p>ZenJar allows you to integrate with various third-party services (e.g., Google Calendar, Google Tasks, Slack, Discord).</p>
                    <h3 className="font-headline">Third-Party Terms</h3>
                    <p>Your use of third-party services is governed by their respective terms of service and privacy policies. We are not responsible for the practices of third-party services.</p>
                    <h3 className="font-headline">Authorization</h3>
                    <p>By enabling an integration, you authorize ZenJar to access and exchange data with that third-party service as necessary to provide the integrated functionality.</p>

                    <h2 className="font-headline">8. Intellectual Property</h2>
                    <h3 className="font-headline">App Content</h3>
                    <p>All content, features, and functionality of the App (excluding user-generated content), including but not limited to text, graphics, logos, icons, images, software, and the design, selection, and arrangement thereof, are the exclusive property of ZenJar and are protected by copyright, trademark, and other intellectual property laws.</p>
                    <h3 className="font-headline">Trademarks</h3>
                    <p>The ZenJar name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of ZenJar or its affiliates or licensors. You must not use such marks without our prior written permission.</p>

                    <h2 className="font-headline">9. Disclaimers</h2>
                    <p>THE ZENJAR APP IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, SECURE, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE MAKE NO WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY CONTENT OR INFORMATION OBTAINED THROUGH THE APP, INCLUDING AI-GENERATED CONTENT.</p>

                    <h2 className="font-headline">10. Limitation of Liability</h2>
                    <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL ZENJAR, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE APP; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE APP; (III) ANY CONTENT OBTAINED FROM THE APP; AND (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
                    <p>OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE APP WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU HAVE PAID TO ZENJAR FOR THE APP IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).</p>

                    <h2 className="font-headline">11. Termination</h2>
                    <p>We may terminate or suspend your access to the App immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use the App will immediately cease. If you wish to terminate your account, you may do so through the App's settings or by contacting us.</p>

                    <h2 className="font-headline">12. Governing Law and Dispute Resolution</h2>
                    <p>These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction, e.g., the State of California, without regard to its conflict of law principles].</p>
                    <p>Any dispute arising out of or relating to these Terms or the App shall be resolved exclusively in the state or federal courts located in [Your City, Your State, e.g., San Francisco, California].</p>

                    <h2 className="font-headline">13. Changes to These Terms</h2>
                    <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our App after those revisions become effective, you agree to be bound by the revised terms.</p>

                    <h2 className="font-headline">14. Contact Us</h2>
                    <p>If you have any questions about these Terms, please contact us at:</p>
                    <p>
                        <a href="mailto:help@trespiesdesign.com">help@trespiesdesign.com</a><br/>
                        <a href="https://zenjarapp.com" target="_blank" rel="noopener noreferrer">zenjarapp.com</a>
                    </p>
                </CardContent>
            </Card>
        </div>
    );
}
