// This is an autogenerated file from Firebase Studio. Do not edit.
'use client';
import MainLayout from "@/components/layout/main-layout";

export default function Page() {
  return (
    <MainLayout title="Roadmap">
       <div className="flex flex-col items-center justify-center h-full text-center">
        <h1 className="text-4xl font-bold">Roadmap</h1>
        <p className="text-lg text-muted-foreground mt-2">Coming soon!</p>
      </div>
    </MainLayout>
  )
}
